import { ZARD_ICONS, type ZardIcon } from './icons';

const STYLE_CLASSES = new Set([
  'fa',
  'fas',
  'far',
  'fab',
  'fa-solid',
  'fa-regular',
  'fa-light',
  'fa-duotone',
  'fa-brands',
]);

const NON_ICON_CLASSES = new Set([
  'fa-fw',
  'fa-spin',
  'fa-bounce',
  'fa-pulse',
]);

const FA_TO_ZARD: Record<string, ZardIcon> = {
  'fa-home': 'house',
  'fa-cog': 'settings',
  'fa-cogs': 'settings',
  'fa-user': 'user',
  'fa-users': 'users',
  'fa-user-plus': 'user-plus',
  'fa-user-check': 'badge-check',
  'fa-user-graduate': 'book-open',
  'fa-user-shield': 'shield',
  'fa-user-tag': 'tag',
  'fa-user-tie': 'user',
  'fa-users-cog': 'settings',
  'fa-users-slash': 'circle-x',
  'fa-bell': 'bell',
  'fa-envelope': 'mail',
  'fa-envelope-open-text': 'mail',
  'fa-calendar': 'calendar',
  'fa-calendar-alt': 'calendar',
  'fa-calendar-check': 'circle-check',
  'fa-calendar-days': 'calendar',
  'fa-calendar-plus': 'calendar-plus',
  'fa-clock': 'clock',
  'fa-clock-rotate-left': 'clock',
  'fa-search': 'search',
  'fa-magnifying-glass': 'search',
  'fa-magnifying-glass-chart': 'search',
  'fa-times': 'x',
  'fa-xmark': 'x',
  'fa-times-circle': 'circle-x',
  'fa-check': 'check',
  'fa-check-circle': 'circle-check',
  'fa-check-square': 'circle-check',
  'fa-square': 'square',
  'fa-chevron-down': 'chevron-down',
  'fa-chevron-up': 'chevron-up',
  'fa-chevron-left': 'chevron-left',
  'fa-chevron-right': 'chevron-right',
  'fa-angle-left': 'chevron-left',
  'fa-angle-right': 'chevron-right',
  'fa-angle-double-left': 'chevron-left',
  'fa-angle-double-right': 'chevron-right',
  'fa-arrow-left': 'arrow-left',
  'fa-arrow-right': 'arrow-right',
  'fa-arrow-up': 'arrow-up',
  'fa-arrow-down': 'arrow-down',
  'fa-ellipsis-h': 'ellipsis',
  'fa-ellipsis-v': 'ellipsis',
  'fa-ellipsis-vertical': 'ellipsis',
  'fa-plus': 'plus',
  'fa-minus': 'minus',
  'fa-plus-circle': 'plus',
  'fa-minus-circle': 'minus',
  'fa-folder': 'folder',
  'fa-folder-open': 'folder-open',
  'fa-file': 'file',
  'fa-file-alt': 'file-text',
  'fa-file-lines': 'file-text',
  'fa-file-export': 'file-text',
  'fa-file-import': 'file-text',
  'fa-file-excel': 'file-text',
  'fa-file-invoice-dollar': 'credit-card',
  'fa-file-signature': 'file-text',
  'fa-file-arrow-down': 'file-text',
  'fa-file-search': 'file-text',
  'fa-clipboard': 'clipboard',
  'fa-clipboard-list': 'clipboard',
  'fa-clipboard-check': 'clipboard',
  'fa-chart-bar': 'activity',
  'fa-chart-line': 'activity',
  'fa-chart-pie': 'activity',
  'fa-flag': 'tag',
  'fa-graduation-cap': 'book-open',
  'fa-book': 'book-open',
  'fa-book-open': 'book-open',
  'fa-book-open-reader': 'book-open-text',
  'fa-book-bookmark': 'book-open-text',
  'fa-comments': 'mail',
  'fa-comment': 'mail',
  'fa-comment-dots': 'mail',
  'fa-comment-medical': 'mail',
  'fa-bullhorn': 'bell',
  'fa-exclamation-triangle': 'triangle-alert',
  'fa-triangle-exclamation': 'triangle-alert',
  'fa-exclamation-circle': 'circle-alert',
  'fa-info-circle': 'info',
  'fa-circle-info': 'info',
  'fa-shield-alt': 'shield',
  'fa-shield-check': 'shield',
  'fa-shield-exclamation': 'triangle-alert',
  'fa-shield-halved': 'shield',
  'fa-sun': 'sun',
  'fa-moon': 'moon',
  'fa-palette': 'palette',
  'fa-paper-plane': 'move-right',
  'fa-paperclip': 'tag',
  'fa-upload': 'arrow-up',
  'fa-download': 'arrow-down',
  'fa-location-dot': 'map-pin',
  'fa-map-marker-alt': 'map-pin',
  'fa-phone': 'phone',
  'fa-briefcase': 'folder',
  'fa-building': 'square-library',
  'fa-id-badge': 'badge-check',
  'fa-receipt': 'file-text',
  'fa-save': 'save',
  'fa-right-from-bracket': 'log-out',
  'fa-sign-out-alt': 'log-out',
  'fa-bars': 'panel-left',
  'fa-sliders': 'settings',
  'fa-sliders-h': 'settings',
  'fa-filter-circle-xmark': 'circle-x',
  'fa-bullseye': 'circle',
  'fa-star': 'star',
  'fa-heart': 'heart',
  'fa-history': 'clock',
  'fa-desktop': 'monitor',
  'fa-laptop': 'monitor',
  'fa-tablet-screen-button': 'tablet',
  'fa-mobile-screen-button': 'smartphone',
  'fa-sitemap': 'layers-2',
  'fa-layer-group': 'layers',
  'fa-th': 'layout-dashboard',
  'fa-grid-2': 'layout-dashboard',
  'fa-columns': 'panel-left',
  'fa-school': 'square-library',
  'fa-chalkboard': 'monitor',
  'fa-chalkboard-teacher': 'monitor',
  'fa-chalkboard-user': 'monitor',
  'fa-list': 'list-filter-plus',
  'fa-list-check': 'list-filter-plus',
  'fa-tasks': 'list-filter-plus',
  'fa-pen': 'file-text',
  'fa-pen-square': 'file-text',
  'fa-edit': 'file-text',
  'fa-sync-alt': 'loader-circle',
  'fa-rotate': 'loader-circle',
  'fa-spinner': 'loader-circle',
  'fa-circle': 'circle',
  'fa-circle-check': 'circle-check',
  'fa-door-open': 'move-right',
  'fa-link': 'move-right',
  'fa-people-roof': 'users',
  'fa-money-bill-wave': 'dollar-sign',
  'fa-microchip': 'terminal',
  'fa-signal': 'activity',
};

export function toZardIcon(icon: string): ZardIcon {
  if (!icon) return 'circle';

  const tokens = icon.split(/\s+/).filter(Boolean);
  const iconToken = tokens.find((token) => token.startsWith('fa-') && !STYLE_CLASSES.has(token) && !NON_ICON_CLASSES.has(token));

  if (iconToken && FA_TO_ZARD[iconToken]) {
    return FA_TO_ZARD[iconToken];
  }

  if (iconToken && iconToken in ZARD_ICONS) {
    return iconToken as ZardIcon;
  }

  if (icon in ZARD_ICONS) {
    return icon as ZardIcon;
  }

  return 'circle';
}
